import type { Mesh } from "./tube";

interface NamedMesh {
  name: string;
  material: string;
  mesh: Mesh;
}

const MATERIALS: Record<string, { kd: [number, number, number] }> = {
  body_1: { kd: [1.0, 0.42, 0.42] },
  body_2: { kd: [0.31, 0.8, 0.77] },
  body_3: { kd: [1.0, 0.9, 0.43] },
};

/**
 * Generate OBJ file content from named meshes.
 */
export function generateObj(meshes: NamedMesh[], mtlFilename: string): string {
  const lines: string[] = [
    "# 3-Body Trajectory Mesh",
    "# Generated by fleeting-grace",
    `mtllib ${mtlFilename}`,
    "",
  ];

  let vertexOffset = 0;

  for (const { name, material, mesh } of meshes) {
    if (mesh.vertices.length === 0) continue;

    lines.push(`o ${name}`);
    lines.push(`g ${name}`);
    lines.push(`usemtl ${material}`);

    for (const v of mesh.vertices) {
      lines.push(`v ${v[0].toFixed(6)} ${v[1].toFixed(6)} ${v[2].toFixed(6)}`);
    }

    for (const f of mesh.faces) {
      const i0 = f[0] + 1 + vertexOffset;
      const i1 = f[1] + 1 + vertexOffset;
      const i2 = f[2] + 1 + vertexOffset;
      lines.push(`f ${i0} ${i1} ${i2}`);
    }

    vertexOffset += mesh.vertices.length;
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate MTL file content with body materials.
 */
export function generateMtl(): string {
  const lines: string[] = [];

  for (const [name, { kd }] of Object.entries(MATERIALS)) {
    lines.push(`newmtl ${name}`);
    lines.push(`Kd ${kd[0].toFixed(4)} ${kd[1].toFixed(4)} ${kd[2].toFixed(4)}`);
    lines.push("Ka 0.1000 0.1000 0.1000");
    lines.push("Ks 0.3000 0.3000 0.3000");
    lines.push("Ns 50.0000");
    lines.push("d 1.0000");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Trigger a file download in the browser.
 */
export function downloadFile(content: string, filename: string, mimeType = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
